version: '2.3'

services:
  pd0:
    image: pingcap/pd:v4.0.2
    ports:
      - "2379:2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data/pd0:/data
      - ./log/pd0:/log
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --config=/pd.toml
      - --data-dir=/data
      - --log-file=/log/pd.log
    restart: on-failure
  tikv0:
    image: pingcap/tikv:v4.0.2
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data/tikv0:/data
      - ./log/tikv0:/log
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --pd=pd0:2379
      - --config=/tikv.toml
      - --data-dir=/data
      - --log-file=/log/tikv.log
    depends_on:
      - "pd0"
    restart: on-failure
  tidb0:
    image: pingcap/tidb:v4.0.2
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./log/tidb0:/log
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - --log-file=/log/tidb.log
      - --advertise-address=tidb0
    depends_on:
      - "tikv0"
    restart: on-failure
  tiflash0:
    image: pingcap/tiflash:v4.0.2
    ports:
      - "3930:3930"
      - "9000:9000"
      - "8123:8123"
      - "9009:9009"
      - "20170:20170"
    volumes:
      - ./config/tiflash.toml:/config.toml:ro
      - ./config/tiflash-users.toml:/users.toml:ro
      - ./config/tiflash-proxy.toml:/proxy.toml:ro
      - ./data/tiflash0:/data
      - ./log/tiflash0:/log
    command:
      - --config-file
      - /config.toml
    depends_on:
      - "tidb0"
    restart: on-failure
